#!/usr/bin/env bash

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
AOC_URL=https://adventofcode.com

source $SCRIPT_DIR/.env

main() {
    local year=$1
    local day=$2
    curl -H "Cookie: session=$AOC_SESSION" "$AOC_URL/$year/day/$day/input"
}

main $@
