#!/usr/bin/env bash

AOC_URL=https://adventofcode.com

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source $ROOT_DIR/.env

main() {
    local year=$1
    local day=$2
    curl -H "Cookie: session=$AOC_SESSION" "$AOC_URL/$year/day/$day/input"
}

main $@
