package main

import (
	"testing"
)

func TestBeam(t *testing.T) {
	input := `
	.......S.......
	...............
	.......^.......
	...............
	......^.^......
	...............
	.....^.^.^.....
	...............
	....^.^...^....
	...............
	...^.^...^.^...
	...............
	..^...^.....^..
	...............
	.^.^.^.^.^...^.
	...............
	`
	expected := 40

	result := FireTheBeam(input)

	if result != expected {
		t.Errorf("Expected %d but got %d", expected, result)
	}
}
